### PR TITLE
Fixed bug with missing 'func'

### LINKED ISSUE #448: `func` doesn't always exist in the Pallene entry point
The following program produces a C compiler error. It might be related to #440 and/or #414... We should find out what is the problem is and why the current tests did not catch it.
 

```lua
local m = {}

record Stream
    first: integer
    rest: () -> any
end

local function count_from(n: integer): Stream
    return {
        first = n,
        rest = function() return count_from(n+1) end,
    }
end

return m
```

```
/tmp/lua_cn9Wzz: In function ‘function_03’:
/tmp/lua_cn9Wzz:129:38: error: ‘func’ undeclared (first use in this function); did you mean ‘Pfunc’?
  129 |     x2 = function_02(L, base + 0, G, func->upvalue, x3);
      |                                      ^~~~
      |                                      Pfunc
/tmp/lua_cn9Wzz:129:38: note: each undeclared identifier is reported only once for each function it appears in
internal error: compiler failed
compilation line: cc -I./vm/src -I./runtime -std=c99 -g -fPIC -Wall -Wundef -Wpedantic -Wno-unused -O2 -fverbose-asm -O2  -x c -o '/tmp/lua_ZIUovs' -S '/tmp/lua_cn9Wzz'
```

The error happens inside the Pallene entry point for the lambda:

```c
/* $lambda foo.pln:11 */
static TValue function_03(
    lua_State *L,
    StackValue *base,
    Udata *G,
    TValue * restrict U /* upvalues */
) {
    ptrdiff_t base_offset = savestack(L, base);
    
    TValue x1 = {{0},0};
    Udata *x2;
    lua_Integer x3;
    
    x3 = intop(+, ivalue(&U[1]), 1);
    x2 = function_02(L, base + 0, G, func->upvalue, x3);   // <---- HERE
    base = restorestack(L, base_offset);
    setuvalue(L, &x1, x2);
    return x1;
}
```

### PR DESCRIPTION
**Pull request by srijan-paul**
Fixes #448 
`CallStatic` is always used in pallene-to-pallene calls. It is worth noting that currently all calls to closures that may have upvalues is always done via CallDyn, so we can safely pass `NULL` in every CallStatic for the `TValue* U` parameter.

### CODE REVIEW

File: pallene/coder.lua [hunk 1]
```diff
@@ -1398,8 +1398,12 @@ gen_cmd["CallStatic"] = function(self, cmd, func)
     local top = self:stack_top_at(func, cmd)
 
     local parts = {}
-    table.insert(parts, self:call_pallene_function(dsts, #func.captured_vars >= 1,
-        cmd.f_id, top, xs))
+
+    -- CallStatic is used in pallene-pallene calls. Any calls to higher order functions or
+    -- closures is always done using CallDyn at the moment, meaning CallStatic will never call
+    -- a closure with upvalues.
```
Comment (hugomg) [inline pallene/coder.lua:1404]: I'm not sure that this assumption will still hold after next week. Once we split the `G`, the global variables will become upvalues.

Instead of the `call_pallene_function` receiving a `has_upvalue`, it should receive a string with a `C` expression for the `CClosure*`. In the Lua entry point that is the `func`, but in the Pallene entry point it will be something else.  (Currently, the `"func"` in the `call_pallene_function` assumes that we're inside a Lua entry point, which doesn't smell right)

I think that the `call_pallene_function` should be able to know how many upvalues the function has, based on the `f_id`. We might be able to do the NULL optimization inside the `call_pallene_function`, instead of in the places that call it.

**Review by hugomg — CHANGES_REQUESTED** [review]
I have a feeling that this solution will break after we split the `G`. Do you agree?

**Comment by srijan-paul** [comment]
> I have a feeling that this solution will break after we split the G. Do you agree?

Yes, since toplevel functions would also be closures.

File: pallene/coder.lua [hunk 2]
```diff
@@ -479,13 +479,25 @@ function Coder:pallene_entry_point_definition(f_id)
...
+    local func       = self.module.functions[f_id]
+    local n_upvalues = #func.captured_vars
 
     local args = {}
     table.insert(args, "L")
     table.insert(args, base)
     table.insert(args, "G")
-    table.insert(args, has_upvalue and "func->upvalue" or "NULL")
+
+    local upvals
```
Comment (hugomg) [inline pallene/coder.lua:492]: If I were not familiar with this optimization, I would have guessed that the reason for the NULL is because the upvalue array doesn't exist when there are no captured variables. Which is not the real reason...

Maybe we should add a comment saying that this NULL thing an optimization.

File: pallene/coder.lua [hunk 3]
```diff
@@ -479,13 +479,25 @@ function Coder:pallene_entry_point_definition(f_id)
...
+    if n_upvalues >= 1 then
+        assert(cclosure)
```
Comment (hugomg) [inline pallene/coder.lua:494]: If the `cclosure`  is no longer optional (see my other comments) then I think we should also remove this assert.

File: pallene/coder.lua (hunk 1 above)
Comment (hugomg) [reply pallene/coder.lua:1414]: At some point, the call static functions certainly will start having upvalues too. Either after we split the `G`, or after we implement #414, whichever comes first.

At the very least, we need to rewrite this comment. While this might be true today, it certalny won't be true anymore in the near future. However, I feel that maybe we should bite the bullet and try to allow upvalues here as well.

The impression I'm having here is that the only reason we added the assert, is to avoid having to come up with a reference to the cclosure. However, getting that cclosure is going to be a pre-requesite for #413. I suppose we might as well do it now...

File: pallene/coder.lua [hunk 4]
```diff
@@ -1398,8 +1408,12 @@ gen_cmd["CallStatic"] = function(self, cmd, func)
...
 
     local parts = {}
-    table.insert(parts, self:call_pallene_function(dsts, #func.captured_vars >= 1,
-        cmd.f_id, top, xs))
+
+    -- CallStatic is used in pallene-pallene calls. Any calls to higher order functions or
+    -- closures is always done using CallDyn at the moment, meaning CallStatic will never call
+    -- a closure with upvalues.
+    assert(#self.module.functions[cmd.f_id].captured_vars == 0)
+    table.insert(parts, self:call_pallene_function(dsts, cmd.f_id, top, xs))
```
Comment (hugomg) [inline pallene/coder.lua:1416]: I recommend using optional arguments sparingly. In a dynamic language, it's harder to tell if a missing argument is intentional or if it is an accident. In this case I would prefer passing an explicit `false` for the missing argument.

That said, as I said elsewhere, I think it would be even better if the `cclosure` argument were always a string. We want to allow CallStatic for functions that have captured variables.

**Review by hugomg — CHANGES_REQUESTED** [review]

File: pallene/coder.lua (hunk 4 above)
Comment (srijan-paul) [reply pallene/coder.lua:1416]: About the `CallStatic` being able to pass upvalues, we'd also have to be able to find a toplevel function's `upvalue` list, provided we know it's `id`. To that end, I have a small question:

Is it always guaranteed that  `function_n` is the `n`th value associated with the `globals` userdata?
If so, then what do you think about exposing the index `globals` and then getting the cclosure from that table?
I am also wondering the amount of overhead this might add to calling toplevel functions that capture globals as upvalues, since we're doing an extra push and pop operation.

```c
int type = lua_getiuservalue(L, globals, n);
assert(type == LUA_TFUNCTION);
// get the `upvalue` list from stack top, then pop from the stack?
lua_pop(L, 1)
```

Comment (hugomg) [reply pallene/coder.lua:1416]: > Is it always guaranteed that function_n is the nth value associated with the globals userdata?

I think we can get this info from `upvalue_of_function`.

I don't remember if we are already creating a closure for every toplevel function. In the past we did not, but I don't remember if we recently changed this.

> I am also wondering the amount of overhead this might add to calling toplevel functions that capture globals as upvalues, since we're doing an extra push and pop operation.

We should't need to use a push and pop operation to get a value from the `G`. We can access the uservalue array directly.

Look at the places in the code that use with ir.Value.Function to see how we're currently dealing with this.

Comment (srijan-paul) [reply pallene/coder.lua:1416]: > I don't remember if we are already creating a closure for every toplevel function. 

We don't create a `CClosure` object for toplevel functions declared like `local function foo`, but we do for `local foo: () -> () = ...`.  I realize now that it might be better to start by fixing this inconsistency first.

However, once that's done, we would still only be able to refer to local functions inside of `$init`.

**Comment by srijan-paul** [comment]
To truly support `CallStatic` being capable of passing cclosures, we might have to implement the `G` splitting first.
I think for this PR we could:
- Only pass the upvalue list for module functions in `gen_cmd["CallStatic"]`. Which won't be used either way I believe.
- For toplevel local functions, we have to first decide upon a consistent behaviour. I think that will mean creating `CClosure`s for them in $init. In other words, treating them as regular toplevel locals?
- Once all toplevel local functions have a cclosure assosciated with them, we have to make sure that other functions can find them, by capturing them as upvalues. This is where it might make sense to do the `G` splitting first.

File: pallene/coder.lua [hunk 5]
```diff
@@ -479,13 +479,26 @@ function Coder:pallene_entry_point_definition(f_id)
     }))
 end
 
-function Coder:call_pallene_function(dsts, has_upvalue, f_id, base, xs)
+function Coder:call_pallene_function(dsts, f_id, base, xs, cclosure)
```
Comment (hugomg) [inline pallene/coder.lua:482]: What do you think about reordering the arguments of `call_pallene_function` so it's more similar to the order of the entry point? Now that `cclosure` is no longer optional, it doesn't have to be the last argument.

File: pallene/print_ir.lua [hunk 6]
```diff
@@ -217,7 +217,7 @@ local function Cmd(cmd)
     elseif tag == "ir.Cmd.NewRecord"  then rhs = "new ".. cmd.rec_typ.name .."()"
     elseif tag == "ir.Cmd.GetField"   then rhs = Field(cmd.src_rec, cmd.field_name)
     elseif tag == "ir.Cmd.SetField"   then rhs = Val(cmd.src_v)
-    elseif tag == "ir.Cmd.CallStatic" then rhs = Call(Fun(cmd.f_id),  Vals(cmd.srcs))
+    elseif tag == "ir.Cmd.CallStatic" then rhs = Call(Fun(cmd.src_f.id),  Vals(cmd.srcs))
```
Comment (hugomg) [inline pallene/print_ir.lua:220]: I get nervous when I see two field accesses in a row, without checking the type tag... In this case we might be able to avoid this if we use `Val(cmd.src_f)` instead of `Fun(cmd.src_f.id)`.

**Review by hugomg — CHANGES_REQUESTED** [review]
Looks good! I only have two small requests....

Next step after those will be the SetUpvalue PR, right?

File: pallene/coder.lua (hunk 5 above)
Comment (srijan-paul) [reply pallene/coder.lua]: Right. That's a good point.

**Review by hugomg — APPROVED** [review]
Perfect!
